INSERT INTO IconTextureAtlases
		(Name,										IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_SAILOR_RANGERCAT_PORTRAIT',	38,			1,				1,				'ICON_SAILOR_RANGERCAT_PORTRAIT_38.dds'),
		('ICON_ATLAS_SAILOR_RANGERCAT_PORTRAIT',	50,			1,				1,				'ICON_SAILOR_RANGERCAT_PORTRAIT_50.dds'),
		('ICON_ATLAS_SAILOR_RANGERCAT_PORTRAIT',	70,			1,				1,				'ICON_SAILOR_RANGERCAT_PORTRAIT_70.dds'),
		('ICON_ATLAS_SAILOR_RANGERCAT_PORTRAIT',	95,			1,				1,				'ICON_SAILOR_RANGERCAT_PORTRAIT_95.dds'),
		('ICON_ATLAS_SAILOR_RANGERCAT_PORTRAIT',	200,		1,				1,				'ICON_SAILOR_RANGERCAT_PORTRAIT_200.dds'),
		('ICON_ATLAS_SAILOR_RANGERCAT_PORTRAIT',	256,		1,				1,				'ICON_SAILOR_RANGERCAT_PORTRAIT_256.dds');

INSERT OR REPLACE INTO IconDefinitions
		(Name,											Atlas,										'Index')
VALUES	('ICON_UNIT_RANGER_PORTRAIT',					'ICON_ATLAS_SAILOR_RANGERCAT_PORTRAIT',		0),
		('ICON_ETHNICITY_ASIAN_UNIT_RANGER_PORTRAIT',	'ICON_ATLAS_SAILOR_RANGERCAT_PORTRAIT',		0),
		('ICON_ETHNICITY_MEDIT_UNIT_RANGER_PORTRAIT',	'ICON_ATLAS_SAILOR_RANGERCAT_PORTRAIT',		0),
		('ICON_ETHNICITY_SOUTHAM_UNIT_RANGER_PORTRAIT',	'ICON_ATLAS_SAILOR_RANGERCAT_PORTRAIT',		0),
		('ICON_ETHNICITY_AFRICAN_UNIT_RANGER_PORTRAIT',	'ICON_ATLAS_SAILOR_RANGERCAT_PORTRAIT',		0);